version: '3'
services:
  cron:
    image: nutellinoit/magento2-cron
    depends_on:
      - apache
      - varnish
    links:
      - db
      - cache
      - clusterdata
      - apache
      - varnish
    volumes:
      - ./magento2:/var/www/html
      - ./varnish.secret:/varnish.secret
      # Enable the next line if you want to add a custom php.ini
      #- ./php.ini:/usr/local/etc/php/conf.d/999-customphp.ini


  varnish:
    image: nutellinoit/varnish
    ports:
      - "80:80"
      - "6082:6082"
    depends_on:
      - apache
    links:
      - apache
    volumes:
      - ./varnish.vcl:/etc/varnish/default.vcl
      - ./varnish.secret:/etc/varnish/secret
    environment:
      - CACHE_SIZE=256M

  apache:
    image: nutellinoit/magento2-apache-php
    depends_on:
      - db
      - cache
      - clusterdata
    links:
      - db
      - cache
      - clusterdata
    volumes:
      - ./magento2:/var/www/html
      - ~/.composer/auth.json:/root/.composer/auth.json
      # Enable the next line if you want to add a custom php.ini
      #- ./php.ini:/usr/local/etc/php/conf.d/999-customphp.ini

  db:
    image: mariadb
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=magento2
      - MYSQL_DATABASE=magento2
      - MYSQL_USER=magento2
      - MYSQL_PASSWORD=magento2

  cache:
    image: nutellinoit/redis-volatile

  clusterdata:
    image: nutellinoit/redis-volatile

volumes:
  dbdata:
