version: '2'
services:

  applications:
    image: tianon/true


  cron:
    image: nutellinoit/magento2-cron
    depends_on:
      - apache
      - varnish
    links:
      - db
      - cache
      - clusterdata
      - apache
      - varnish
    volumes:
      - ./magento2-files:/var/www/html
      - ./varnish.secret:/varnish.secret
      - ./auth.json:/var/www/.composer/auth.json
      # Enable the next line if you want to add a custom php.ini
      #- ./php.ini:/usr/local/etc/php/conf.d/999-customphp.ini
    networks:
      main:
        aliases:
          - cron


  varnish:
    image: nutellinoit/varnish
    ports:
      - "80:80"
      - "6082:6082"
    depends_on:
      - apache
    links:
      - apache
    volumes:
      - ./varnish.vcl:/etc/varnish/default.vcl
      - ./varnish.secret:/etc/varnish/secret
    environment:
      - CACHE_SIZE=256M
    networks:
      main:
        aliases:
          - varnish
  apache:
    image: nutellinoit/magento2-apache-php
    depends_on:
      - db
      - cache
      - clusterdata
    links:
      - db
      - cache
      - clusterdata
    volumes_from:
      - applications
    volumes:
      - ./magento2-files:/var/www/html
      - ./auth.json:/var/www/.composer/auth.json
      # Enable the next line if you want to add a custom php.ini
      #- ./php.ini:/usr/local/etc/php/conf.d/999-customphp.ini
    networks:
      main:
        aliases:
          - apache

  db:
    image: mariadb
    user: mysql
    ports:
      - "3306:3306"
    volumes:
      - ./dbdata/:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=magento2
      - MYSQL_DATABASE=magento2
      - MYSQL_USER=magento2
      - MYSQL_PASSWORD=magento2
    networks:
      main:
        aliases:
          - db

  cache:
    image: nutellinoit/redis-volatile
    networks:
      main:
        aliases:
          - cache

  clusterdata:
    image: nutellinoit/redis-volatile
    networks:
      main:
        aliases:
          - clusterdata
  #lets-nginx:
  #  image:  smashwilson/lets-nginx
  #  restart: always
  #  volumes:
  #    - "./cache:/cache"
  #    - "./letsencrypt:/etc/letsencrypt"
  #  links:
  #    - varnish
  #  environment:
  #    EMAIL: "assistenza@busnet.it"
  #    DOMAIN: "fcrdev.netribe.it"
  #    UPSTREAM: "varnish:80"
  #  ports:
  #    - "80:80"
  #    - "443:443"
  #  networks:
  #    main:
  #      aliases:
  #        - lets-nginx
  backup_db_magento2:
    restart: always
    image: registry.busnet.it/busnet/backup_db_magento2:1.0
    volumes:
          - ./backup_db_magento2/:/backup/
          - ./script_backup_magento2.sh:/script.sh
    networks:
      main:
        aliases:
          - backup_db_magento2
volumes:
  dbdata:

networks:
  main:
